name: Java CI

on:
    push:
        branches: [ test ]
    pull_request:
        branches: [ test ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'
                  cache: 'maven'
                  maven-version: '3.9.11'

            - name: Verify Java version
              run: | 
                  java -version
                  mvn -version

            - name: Build with Maven
              run: mvn -B clean package --file pom.xml

            - name: Artifacts location
              run: ls -R target

            - name: SonarQube Scan
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
                -Dsonar.projectKey=java-api-microservice-svc \
                -Dsonar.organization=mahendra \
                -Dsonar.host.url=http://34.229.97.14:9000 \
                -Dsonar.login=${{ secrets.SONAR_TOKEN }}